# Generated by Django 5.1.7 on 2025-03-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_remove_department_no_of_student_department_dpt_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='no_of_student',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
