# Generated by Django 5.1.7 on 2025-03-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_alter_student_no_of_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='no_of_student',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
