# Generated by Django 5.1.6 on 2025-03-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_alter_student_no_of_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='no_of_student',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
